### ISSUE TITLE
RFC: v1.0.0 api and feature set

### ISSUE THREAD

**Issue by jtrussell** [iVantage/angular-ivh-treeview#27]
In our opinion this directive has reached a level of maturity and stability such that we'd like to nail down the api and feature set with a shiny new major version number. This is a request for comments on anything related to desired features, api changes, examples/documentation, etc. that should be addressed before that happens.

Here's our short list of items:

### Features and Fixes

- [x] Allow for programmatic expand/collapse (#24)
- [x] Make node templates customizable (#25)
- [x] Be able to configure all options independently (#32)
- [x] Rename "click" handler to "toggle" (#45)
- [x] Investigate swapping callbacks to be expression based (#55)

### Examples and Demos

*E.g. create a jsbin from the template in the README for...*

- [x] Default selected state/validate on startup (#26)
  - [x] Programmatic expand/collapse
- [x] Custom Node Templates
  - [x] Global template
  - [x] Inline template
  - [x] Options hash template
  - [x] Transcluded template
- [x] Custom inline template (as option)
- [x] Custom inline template (as transcluded content)
- [x] Toggle Handler
- [x] Change Handler (fix for new syntax)
- [x] `ivhTreeviewMgr` *dot*
  - [x] `select` / `deselect`
  - [x] `selectAll` / `deselectAll`
  - [x] `selectEach` / `deselectEach`
  - [x] `expandTo` / `collapseParents`
  - [x] `expandRecursive` / `collapseParents`
  - [x] `validate`

### Documentation

- [x] Document which classes are provided on which elements. E.g. `ivh-treeview-node-label`, etc. (#44)
- [x] Better site (`gh-pages` branch in progress). (#46)

Things to consider making opt-in/opt-out-able:

- Watching children lengths for changes, for large static trees this is a fair bit of unnecessary watching.
- Inline tuple declarations, again a lot of extra checks for something that may not be used very often

### Possible optimizations...

- Only render child nodes when parent is expanded (#62)
- `ivhTreeviewMgr.sanitize` - Sanitize a node, i.e. remove all treeview attributes
